name: Gyro

targets:
  Gyro:
    sources: Gyro
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "wakewakame.QuadDump"
        CODE_SIGN_STYLE: Manual
      configs:
        debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: QuadDumpProvisioningProfileDebug
          DEVELOPMENT_TEAM: 67762NVFY8
        release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: QuadDumpProvisioningProfile
          DEVELOPMENT_TEAM: 67762NVFY8
