name: Gyro

targets:
  Gyro:
    sources: Gyro
    platform: iOS
    type: application
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "wakewakame.tmp.Gyro"
        CODE_SIGN_STYLE: Manual
      configs:
        debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: DevTemporary
          DEVELOPMENT_TEAM: 67762NVFY8
        release:
          CODE_SIGN_IDENTITY: iPhone Develop
          PROVISIONING_PROFILE_SPECIFIER: DevTemporary
          DEVELOPMENT_TEAM: 67762NVFY8
